# Generated by Django 3.2.3 on 2021-05-19 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('florista', '0002_auto_20210519_1030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='name',
        ),
    ]
