# Generated by Django 3.2.3 on 2021-05-19 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('florista', '0003_remove_cartitem_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='ref_code',
        ),
    ]
